/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.customer;

import LoginAccount.PESystem;
import LoginAccount.User;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.main.Login_Doctor_Search;

/**
 *
 * @author TANKLI
 */
public class Main extends javax.swing.JPanel {

        JPanel userProcessContainer;
        User account;
        PESystem system;

        public Main(JPanel userProcessContainer, User account, PESystem system) {
                initComponents();
                this.userProcessContainer = userProcessContainer;
                this.account = account;
                this.system = system;
                txtName.setText(account.getName());
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnNewExamination = new javax.swing.JButton();
                btnHistory = new javax.swing.JButton();
                btnInformation = new javax.swing.JButton();
                Back = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                txtName = new javax.swing.JTextField();

                btnNewExamination.setText("Create New Examination");
                btnNewExamination.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNewExaminationActionPerformed(evt);
                        }
                });

                btnHistory.setText("Examination History");
                btnHistory.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHistoryActionPerformed(evt);
                        }
                });

                btnInformation.setText("User Information");
                btnInformation.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnInformationActionPerformed(evt);
                        }
                });

                Back.setText("Back");
                Back.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BackActionPerformed(evt);
                        }
                });

                jLabel1.setText("Customer Name:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnNewExamination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(Back))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(123, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Back)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(btnNewExamination)
                                .addGap(18, 18, 18)
                                .addComponent(btnHistory)
                                .addGap(18, 18, 18)
                                .addComponent(btnInformation)
                                .addContainerGap(110, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnNewExaminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewExaminationActionPerformed
                // TODO add your handling code here:

                CreateNewExamination mod = new CreateNewExamination(userProcessContainer, account, system);
                userProcessContainer.add("Login_Customer_Search", mod);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

        }//GEN-LAST:event_btnNewExaminationActionPerformed

        private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
                // TODO add your handling code here:
                userProcessContainer.remove(this);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.previous(userProcessContainer);
        }//GEN-LAST:event_BackActionPerformed

        private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed

                ExaminationHistory mod = new ExaminationHistory( userProcessContainer,  account,  system);
                userProcessContainer.add("ExaminationHistory", mod);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
  
        }//GEN-LAST:event_btnHistoryActionPerformed

        private void btnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationActionPerformed
                // TODO add your handling code here:
               Main_PersonalInformation mod = new Main_PersonalInformation( userProcessContainer,  account,  system);
                userProcessContainer.add("Main_PersonalInformation", mod);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                
        }//GEN-LAST:event_btnInformationActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton Back;
        private javax.swing.JButton btnHistory;
        private javax.swing.JButton btnInformation;
        private javax.swing.JButton btnNewExamination;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JTextField txtName;
        // End of variables declaration//GEN-END:variables
}
