/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

import LoginAccount.PESystem;
import LoginAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TANKLI
 */
public class Login_Customer extends javax.swing.JPanel {

        private JPanel userProcessContainer;
        private User userAccount;
        private PESystem system;

        public Login_Customer(JPanel userProcessContainer, User useraccount, PESystem system) {
                initComponents();
                this.userAccount = userAccount;
                this.userProcessContainer = userProcessContainer;
                this.system = system;
                refreshTable();
                
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnBack = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblUser = new javax.swing.JTable();
                btnSearch = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                btnDelete = new javax.swing.JButton();

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                tblUser.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Name", "ID", "Gender", "Age"
                        }
                ));
                jScrollPane1.setViewportView(tblUser);

                btnSearch.setText("Search");
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSearchActionPerformed(evt);
                        }
                });

                jLabel1.setText("User Information In Physical Examination Center");

                btnDelete.setText("Delete");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnBack)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete))
                                        .addComponent(jLabel1))
                                .addContainerGap(57, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearch)
                                        .addComponent(btnDelete))
                                .addContainerGap(46, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                userProcessContainer.remove(this);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.previous(userProcessContainer);
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                // TODO add your handling code here:
                 Login_Customer_Search mod = new Login_Customer_Search(userProcessContainer, system);
                userProcessContainer.add("Login_Customer_Search", mod);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                
        }//GEN-LAST:event_btnSearchActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                // TODO add your handling code here:
                 int row = tblUser.getSelectedRow();
                if (row < 0) {
                        JOptionPane.showMessageDialog(null, "Please select a row from the table first", " warning", JOptionPane.WARNING_MESSAGE);
                        return;
                }
                User user = (User) tblUser.getValueAt(row, 0);
                system.getCustomerDirectory().getCustomerDirectory().remove(user);
                refreshTable();
        }//GEN-LAST:event_btnDeleteActionPerformed

        public void refreshTable() {
                DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
                model.setRowCount(0);
                for (User u : system.getCustomerDirectory().getCustomerDirectory()) {
                        Object row[] = new Object[4];
                        row[0] = u;
                        row[1] = u.getID();
                        row[2] = u.getGender();
                        row[3] = u.getAge();
                        model.addRow(row);
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnSearch;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblUser;
        // End of variables declaration//GEN-END:variables
}
