/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

/**
 *
 * @author TANKLI
 */
public class LoginEnterpriseDirectory_Create extends javax.swing.JPanel {

        /**
         * Creates new form SystemAdmin_create
         */
        public LoginEnterpriseDirectory_Create() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                loginJButton = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                loginJButton1 = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                txtName = new javax.swing.JTextField();

                loginJButton.setText("Back");
                loginJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButtonActionPerformed(evt);
                        }
                });

                jLabel1.setText("Create New Location: ");

                loginJButton1.setText("Create");
                loginJButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButton1ActionPerformed(evt);
                        }
                });

                jLabel2.setText("Name:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(loginJButton1)
                                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(63, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(loginJButton1)
                                .addContainerGap(121, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

//                String userName = userNameJTextField.getText();
//                char[] passwordCharArray = passwordField.getPassword();
//                String password = String.valueOf(passwordCharArray);
//
//                UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
//
//                if (userAccount == null) {
//
//                        JOptionPane.showMessageDialog(null, "Invalid credentials");
//                        return;
//                } else {
//                        CardLayout layout = (CardLayout) container.getLayout();
//                        container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, system));
//                        layout.next(container);
//                }
//
//                loginJButton.setEnabled(false);
//                logoutJButton.setEnabled(true);
//                userNameJTextField.setEnabled(false);
//                passwordField.setEnabled(false);
        }//GEN-LAST:event_loginJButtonActionPerformed

        private void loginJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_loginJButton1ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JButton loginJButton;
        private javax.swing.JButton loginJButton1;
        private javax.swing.JTextField txtName;
        // End of variables declaration//GEN-END:variables
}
