/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

/**
 *
 * @author TANKLI
 */
public class LoginEnterpriseDirectory extends javax.swing.JPanel {

        /**
         * Creates new form SystemAdmin
         */
        public LoginEnterpriseDirectory() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                loginJButton = new javax.swing.JButton();
                jComboBox1 = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                loginJButton3 = new javax.swing.JButton();
                loginJButton4 = new javax.swing.JButton();
                loginJButton5 = new javax.swing.JButton();

                loginJButton.setText("Back");
                loginJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButtonActionPerformed(evt);
                        }
                });

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical Examination 1", "Physical Examination 2", "Physical Examination 3", "Physical Examination 4" }));

                jLabel1.setText("Choose your location: ");

                loginJButton3.setText("Review");
                loginJButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButton3ActionPerformed(evt);
                        }
                });

                loginJButton4.setText("Create");
                loginJButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButton4ActionPerformed(evt);
                        }
                });

                loginJButton5.setText("Delete");
                loginJButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButton5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(loginJButton3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(loginJButton4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(loginJButton5))
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(102, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(loginJButton3)
                                        .addComponent(loginJButton4)
                                        .addComponent(loginJButton5))
                                .addContainerGap(178, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

//                String userName = userNameJTextField.getText();
//                char[] passwordCharArray = passwordField.getPassword();
//                String password = String.valueOf(passwordCharArray);
//
//                UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
//
//                if (userAccount == null) {
//
//                        JOptionPane.showMessageDialog(null, "Invalid credentials");
//                        return;
//                } else {
//                        CardLayout layout = (CardLayout) container.getLayout();
//                        container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, system));
//                        layout.next(container);
//                }
//
//                loginJButton.setEnabled(false);
//                logoutJButton.setEnabled(true);
//                userNameJTextField.setEnabled(false);
//                passwordField.setEnabled(false);
        }//GEN-LAST:event_loginJButtonActionPerformed

        private void loginJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton3ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_loginJButton3ActionPerformed

        private void loginJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton4ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_loginJButton4ActionPerformed

        private void loginJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_loginJButton5ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JButton loginJButton;
        private javax.swing.JButton loginJButton3;
        private javax.swing.JButton loginJButton4;
        private javax.swing.JButton loginJButton5;
        // End of variables declaration//GEN-END:variables
}
