/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

import LoginAccount.DoctorDirectory;
import LoginAccount.PESystem;
import LoginAccount.User;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author TANKLI
 */
public class Login extends javax.swing.JPanel {

        private JPanel userProcessContainer;
        private User userAccount;
        private PESystem system;

        public Login(JPanel userProcessContainer, User useraccount, PESystem system) {
                initComponents();

                this.userAccount = useraccount;
                this.userProcessContainer = userProcessContainer;
                this.system = system;
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnCenter = new javax.swing.JButton();
                btnDoctor = new javax.swing.JButton();
                btnUser = new javax.swing.JButton();

                btnCenter.setText("Center Directory");
                btnCenter.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCenterActionPerformed(evt);
                        }
                });

                btnDoctor.setText("Doctor Directory");
                btnDoctor.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDoctorActionPerformed(evt);
                        }
                });

                btnUser.setText("User Directory");
                btnUser.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUserActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCenter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(100, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnDoctor)
                                .addGap(18, 18, 18)
                                .addComponent(btnUser)
                                .addGap(18, 18, 18)
                                .addComponent(btnCenter)
                                .addContainerGap(112, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed

            Login_Doctor vpdjp = new Login_Doctor(userProcessContainer, userAccount, system);
            userProcessContainer.add("Login_Doctor", vpdjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDoctorActionPerformed

        private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
                // TODO add your handling code here:

                Login_Customer vpdjp = new Login_Customer(userProcessContainer, userAccount, system);
                userProcessContainer.add("Login_User", vpdjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
        }//GEN-LAST:event_btnUserActionPerformed

        private void btnCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenterActionPerformed
                // TODO add your handling code here:

                Login_Center vpdjp = new Login_Center(userProcessContainer, userAccount, system);
                userProcessContainer.add("Login_Center", vpdjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
        }//GEN-LAST:event_btnCenterActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCenter;
        private javax.swing.JButton btnDoctor;
        private javax.swing.JButton btnUser;
        // End of variables declaration//GEN-END:variables
}
