/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

/**
 *
 * @author TANKLI
 */
public class Login_User extends javax.swing.JPanel {

        /**
         * Creates new form Login_User
         */
        public Login_User() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                loginJButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton1 = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                loginJButton.setText("Back");
                loginJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginJButtonActionPerformed(evt);
                        }
                });

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "ID", "Name", "Gender", "Age"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                jButton1.setText("Search");

                jLabel1.setText("User Information In Physical Examination Center");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginJButton)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1)
                                        .addComponent(jLabel1))
                                .addContainerGap(57, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addContainerGap(46, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

                String userName = userNameJTextField.getText();
                char[] passwordCharArray = passwordField.getPassword();
                String password = String.valueOf(passwordCharArray);

                UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

                if (userAccount == null) {

                        JOptionPane.showMessageDialog(null, "Invalid credentials");
                        return;
                } else {
                        CardLayout layout = (CardLayout) container.getLayout();
                        container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, system));
                        layout.next(container);
                }

                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);
                userNameJTextField.setEnabled(false);
                passwordField.setEnabled(false);
        }//GEN-LAST:event_loginJButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JButton loginJButton;
        // End of variables declaration//GEN-END:variables
}
